name: COVID-QA

acquisition:
    source:
      URL: "https://raw.githubusercontent.com/deepset-ai/COVID-QA/refs/heads/master/data/question-answering/COVID-QA.json"
      target: "datasets/COVID-QA/COVID-QA.json"


